run:
  timeout: 1m

linters-settings:
  errcheck:
    check-type-assertions: true
    exclude-functions:
      github.com/aws/aws-xray-sdk-go/xray.AddAnnotation

  exhaustive:
    check:
      - switch
      - map

  funlen:
    lines: 100
    statements: 50
    ignore-comments: true

  govet:
    enable-all: true
    disable:
      - fieldalignment # rule is too strict

  nolintlint:
    require-explanation: true
    require-specific: true

linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - cyclop
    - dupl
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - execinquery
    - exhaustive
    - exportloopref
  # - forbidigo # Disabling for now until we introduce structured logging
    - funlen
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - goimports
    - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - loggercheck
    - makezero
    - mirror
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
  # - nonamedreturns # Disabling for now until we introduce structured logging (and pull out xray)
    - nosprintfhostport
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tenv
    - testableexamples
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace 